const i18Obj = {
    'en': {
      'skills': 'Skills',
      'portfolio': 'Portfolio',
      'video': 'Video',
      'price': 'Price',
      'contacts': 'Contacts',
      'hero-title': 'Alexa Rise',
      'hero-text': 'Save sincere emotions, romantic feelings and happy moments of life together with professional photographer Alexa Rise',
      'hire': 'Hire me',
      'skill-title-1': 'Digital photography',
      'skill-text-1': 'High-quality photos in the studio and on the nature',
      'skill-title-2': 'Video shooting',
      'skill-text-2': 'Capture your moments so that they always stay with you',
      'skill-title-3': 'Rotouch',
      'skill-text-3': 'I strive to make photography surpass reality',
      'skill-title-4': 'Audio',
      'skill-text-4': 'Professional sounds recording for video, advertising, portfolio',
      'winter': 'Winter',
      'spring': 'for Kate',
      'summer': 'Lucas',
      'autumn': 'Autumn',
      'price-description-1-span-1': 'One location',
      'price-description-1-span-2': '120 photos in color',
      'price-description-1-span-3': '12 photos in retouch',
      'price-description-1-span-4': 'Readiness 2-3 weeks',
      'price-description-1-span-5': 'Make up, visage',
      'price-description-2-span-1': 'One or two locations',
      'price-description-2-span-2': '200 photos in color',
      'price-description-2-span-3': '20 photos in retouch',
      'price-description-2-span-4': 'Readiness 1-2 weeks',
      'price-description-2-span-5': 'Make up, visage',
      'price-description-3-span-1': 'Three locations or more',
      'price-description-3-span-2': '300 photos in color',
      'price-description-3-span-3': '50 photos in retouch',
      'price-description-3-span-4': 'Readiness 1 week',
      'price-description-3-span-5': 'Make up, visage, hairstyle',
      'order': 'Order shooting',
      'contact-me': 'Contact me',
      'send-message': 'Send message',
      'email': 'E-mail',
      'phone': 'Phone',
      'message': 'Message'
    },
    'ukr': {
      'skills': 'Навички',
      'portfolio': 'Портфоліо',
      'video': 'Відео',
      'price': 'Ціни',
      'contacts': 'Контакти',
      'hero-title': 'Алекса Райс',
      'hero-text': 'Збережіть щирі емоції, романтичні переживання та щасливі моменти життя разом із професійним фотографом а Катя нашечка ♡',
      'hire': 'Запросити',
      'skill-title-1': 'Фотографія',
      'skill-text-1': 'Високоякісні фото у студії та на природі',
      'skill-title-2': 'Відеозйомка',
      'skill-text-2': 'Збережіть найкращі моменти, щоб вони завжди залишалися з вами',
      'skill-title-3': 'Ретуш',
      'skill-text-3': 'Я прагну до того, щоб фотографія перевершувала реальність Катя мілашечка ♡',
      'skill-title-4': 'Звук',
      'skill-text-4': 'Професійний запис звуку для відео, реклами, портфоліо',
      'winter': 'Зима',
      'spring': 'Для Каті',
      'summer': 'Лукас',
      'autumn': 'Осінь',
      'price-description-1-span-1': 'Одна локація',
      'price-description-1-span-2': '120 кольорових фото',
      'price-description-1-span-3': '12 отретушированих фото',
      'price-description-1-span-4': 'Готовність через 2-3 неділі',
      'price-description-1-span-5': 'Макіяж, візаж',
      'price-description-2-span-1': 'Одна-дві локації',
      'price-description-2-span-2': '200 кольорових фото',
      'price-description-2-span-3': '20 отретушированих фото',
      'price-description-2-span-4': 'Готовність через 1-2 неділі',
      'price-description-2-span-5': 'Макіяж, візаж',
      'price-description-3-span-1': 'Три локації і більше',
      'price-description-3-span-2': '300 кольорових фото',
      'price-description-3-span-3': '50 отретушированих фото',
      'price-description-3-span-4': 'Готовність через 1 неділю',
      'price-description-3-span-5': 'Макіяж, візаж, зачіска',
      'order': 'Замовити зйомку',
      'contact-me': "Зв'яжіться зі мною",
      'send-message': 'Відправити',
      'email': 'Електронна пошта',
      'phone': 'Ваш телефон',
      'message': 'Повідомлення'
  
    }
  }

export default i18Obj;
  